{% set version = "v0.9.2" %}
{% set name = "baobzi" %}
{% set sha256 = "59ba581de91d88182d8795c48edaeee53a0cdefbd41c1a288b1cfdd08aff60ea" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/flatironinstitute/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py2k]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.14
  host:
    - python
    - pip
    - setuptools
    - ninja
    - wheel
    - scikit-build
  run:
    - python
    - numpy

test:
  imports:
    - baobzi

about:
  home: http://github.com/flatironinstitute/baobzi
  license: Apache-2.0
  license_file: LICENSE
  summary: An adaptive fast function approximator based on tree search.
  description: |
    baobzi is a tool to convert very CPU intensive function calculations into relatively cheap
    ones (at the cost of memory). This is similar to functions like chebeval in MATLAB, but can
    be significantly faster since the order of the polynomial fit can be much much lower to
    meet similar tolerances. It also isn't constrained for use only in MATLAB.

extra:
  recipe-maintainers:
    - blackwer
